version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-laravel-app
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: myapp
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/var/www
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: my-laravel-db
    restart: unless-stopped
    tty: true
    ports:
        - "3307:3306"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: my-laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: my-vue-app
    restart: unless-stopped
    tty: true
    ports:
      - 8081:8080
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
